ecomprj/urls.py
from django.contrib import admin 
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path("__reload__/", include("django_browser_reload.urls")),
     path("",include('store.urls')),
     path("vendor/",include('vendor.urls')),
     path("ckeditor5/",include('django_ckeditor_5.urls'))
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views as storeview

app_name='store'

urlpatterns=[
    path("",storeview.home,name="homepage"),
    path("products/<slug:category_slug>",storeview.product_page,name="products"),
    path("detail/<slug>/",storeview.product_detail,name="products_detail"),
    path("add_to_cart/",storeview.add_to_cart,name="add_to_cart"),
]

store/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils import timezone
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

from userauth import models as user_models
# from vendor import models as vendor_models
# Create your models here.


import shortuuid

STATUS ={
    ("published","published"),
    ("draft","draft"),
    ("disabled","disabled"),
}

PAYMENT_STATUS ={
    ("paid","paid"),
    ("processing","processing"),
    ("failed","failed"),
}

PAYMENT_METHOD ={
    ("paypal","paypal"),
    ("Razorpay","Razorpay"),
    ("Strip","Strip"),
    ("PayU","PayU"),
}

ORDER_STATUS ={
    ("Pending","Pending"),
    ("processing","processing"),
    ("shipped","shipped"),
    ("fulfilled","fulfilled"),
    ("cancelled","cancelled"),
}

SHIPPING_SERVICE ={
    ("DHL","DHL"),
    ("Fedx","fedx"),
    ("UPS","UPS"),
}

RATING={
    (1,"★☆☆☆☆"),
    (2,"★★☆☆☆"),
    (3,"★★★☆☆"),
    (4,"★★★★☆"),
    (5,"★★★★★"),
}

class Category(models.Model):
    title = models.CharField(max_length=200)
    image =models.FileField(upload_to="category", null=True,blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Catagories"
        ordering =['title']


class Product(models.Model):
    name=models.CharField(max_length=255)
    image = models.ImageField(upload_to="images",blank=True,null=True,default="product.jpg")
    description = CKEditor5Field('Text',config_name='extends')

    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,blank=True)
    Brand = models.CharField(max_length=200,null=True,blank=True,verbose_name="Brand Name" )
    price  = models.DecimalField(max_digits=12, decimal_places=0,default=0.0,null=True,blank=True,verbose_name="Sale Price")
    regular_price  = models.DecimalField(max_digits=12, decimal_places=0,default=0.0,null=True,blank=True,verbose_name="Regular price")

    stock = models.PositiveIntegerField(default=0,null=True,blank="published")
    shipping = models.DecimalField(max_digits=12,default=0.00,decimal_places=2 ,null=True,blank=True, verbose_name="Shipping amount")

    status= models.CharField(choices=STATUS,max_length=50,default='published')
    features= models.BooleanField(default=False,verbose_name="Marketplace Features")
    vendor = models.ForeignKey(user_models.User , on_delete=models.SET_NULL ,null=True,blank=True)

    sku = ShortUUIDField(unique=True,length=5,max_length=50, prefix="SKU",alphabet="1234567890")
    slug =models.SlugField(null=True,blank=True)
    
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering =['-id']
        verbose_name_plural = "Product"

    def __str__(self):
        return self.name
    

    def average_rating(self):
        return Review.objects.filter(product=self).aggregate(avg_rating=models.Avg('rating'))['avg_rating']
    
    def reviews(self):
        return Review.objects.filter(product=self)
    
    def gallery(self):
        return Gallery.objects.filter(product=self)
    
    def variants(self):
        return Variant.objects.filter(product=self)
    
    def vendor_orders(self):
        return OrderItem.objects.filter(product=self,vendor=self.vendor)
    
    def percentage(self):
        sale =int(round (100*(self.regular_price-self.price))/self.regular_price)
        return sale

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)+"-"+str(shortuuid.uuid().lower()[:2])
        super(Product, self).save(*args,**kwargs)

class Variant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=1000, verbose_name="Varient Name",null=True, blank=True)

    def items(self):
        return VariantItem.objects.filter(varient=self)
    
    def __str__(self):
        return self.name
    

class VariantItem(models.Model):
    varient = models.ForeignKey(Variant,on_delete=models.CASCADE,related_name='varient_item')
    title = models.CharField(max_length=100, verbose_name="Item Title" , null=True, blank=True)
    content = models.CharField(max_length=1000, verbose_name="Item Content", null=True ,blank=True)

    def __str__(self):
        return self.varient.name
    

class Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    image  = models.FileField(upload_to="images", default="gallery.jpg")
    gallery_id= ShortUUIDField(length= 6, max_length=10, alphabet = '1234567890')

    def ___str__(self):
        return f"{self.product.name} - image"
    
    class Meta:
        verbose_name_plural = "Gallery"
    


class Cart(models.Model):
    product =models.ForeignKey(Product, on_delete=models.CASCADE)
    user= models.ForeignKey(user_models.User, on_delete=models.SET_NULL, null=True,blank=True)
    qty= models.PositiveIntegerField(default=0,null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True, blank=True)
    sub_total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True,blank=True)
    shipping = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True,blank=True)
    tax = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True,blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=12, default=0.00, null=True,blank=True)
    size= models.CharField(max_length=100, null=True, blank=True)
    color= models.CharField(max_length=100, null=True, blank=True)
    cart_id= models.CharField(max_length=1000, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.cart_id}-{self.product.name}"
    

class Coupon(models.Model):
    vendor =models.ForeignKey(user_models.User, on_delete=models.SET_NULL,null=True)
    code = models.CharField(max_length=100)
    discount = models.IntegerField(default=100)

    def __str__(self):
        return self.code
    

class Order(models.Model):
    vendor = models.ManyToManyField(user_models.User , blank=True)
    customer = models.ForeignKey(user_models.User , on_delete=models.SET_NULL, null=True, blank=True, related_name="customer")
    sub_total = models.DecimalField(default=0.00, max_digits=12,decimal_places=2)
    shipping = models.DecimalField(default=0.00, max_digits=12,decimal_places=2)
    tax = models.DecimalField(default=0.00, max_digits=12,decimal_places=2)
    service_fee = models.DecimalField(default=0.00, max_digits=12,decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=12,decimal_places=2)
    payment_status=models.CharField(max_length=100,choices=PAYMENT_STATUS,default="processing")
    payment_method=models.CharField(max_length=100,choices=PAYMENT_METHOD,default=None, null=True,blank=True)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS,default="Pending")
    inital_total = models.DecimalField(max_digits=12,decimal_places=2,default=0.00, help_text="The orginal total")
    saved = models.DecimalField(max_digits=12,decimal_places=2,default=0.00,null=True,blank=True,help_text="Amount")
    # address = models.ForeignKey("customer.address",on_delete=models.SET_NULL,null=True)
    coupon = models.ManyToManyField(Coupon,blank=True)
    order_id = ShortUUIDField(length=6,max_length=25,alphabet = "1234567890")
    payment_id = models.CharField(null=True,blank=True,max_length=1000)
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Order"
        ordering=['-date']

    def __str__(self):
        return self.order_id
    
    def order_item(self):
        return OrderItem.objects.filter(order=self)
        

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS,default="Pending")
    shipping_service = models.CharField(max_length=100, choices=SHIPPING_SERVICE,default=None, null=True, blank=True)
    tracking_id=models.CharField(max_length=100,default=None, null=True,blank=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)
    color= models.CharField(max_length=100, null=True, blank=True)
    size= models.CharField(max_length=100, null=True, blank=True)
    price =models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    sub_total =models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    shipping =models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    tax =models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    total =models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    initial_total =models.DecimalField(max_digits=12,decimal_places=2,default=0.00 , help_text="Grand total of...")
    saved =models.DecimalField(max_digits=12,decimal_places=2,default=0.00 , help_text="Amount",null=True,blank=True)
    coupon = models.ManyToManyField(Coupon,blank=True)
    applied_coupon = models.BooleanField(default=False)
    item_id=ShortUUIDField(length=6,max_length=25,alphabet = "1234567890")
    vendor=models.ForeignKey(user_models.User,on_delete=models.SET_NULL,null=True,related_name="vendor_order_item")
    date = models.DateTimeField(default=timezone.now)

    def order_id(self):
        return f"{self.order.order_id}"
    
    def __str__(self):
        return self.item_id
    
    class Meta:
        ordering = ['-date']
        


class Review(models.Model):
    user = models.ForeignKey(user_models.User,on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, related_name="reviews",null=True)
    review = models.TextField(null=True,blank=True)
    reply = models.TextField(null=True,blank=True)

store/views.py
from decimal import Decimal
from django.shortcuts import render ,get_object_or_404
from store import models as store_model
from store.models import * 
from django.http import JsonResponse
from django.db.models import Q,Avg,Sum

# Create your views here.

def home(request):
    feature_products =store_model.Product.objects.filter(features=True)
    catagory = store_model.Category.objects.all()

    context={
        "feature_products":feature_products,
        "catagory":catagory,
    }
    return render(request,'store/homepage.html',context)

def product_page(request,category_slug):
    category= get_object_or_404(Category, slug=category_slug)
    products= store_model.Product.objects.filter(category=category)
    return render(request,'store/product.html',{'category':category,'products':products})



def product_detail(request,slug):
    product = store_model.Product.objects.get(status="published",slug=slug)
    related_product = store_model.Product.objects.filter(category=product.category,status="published",features=True).exclude(id=product.id)
    product_stock_range = range(1,product.stock+1)
    context ={
        "product":product,
        "related_product":related_product,
        "product_stock_range":product_stock_range
    }
    return render(request,'store/product_detail.html',context)

def add_to_cart(request):
    id = request.GET.get('id')
    qty = request.GET.get('qty')
    color = request.GET.get('color')
    size = request.GET.get('size')
    cart_id = request.GET.get('cart_id')

    request.session['cart_id'] = cart_id

    if not id or not qty or not cart_id:
        return JsonResponse({"error": "No id ,qty or cart_id"},status=400)
    try:
        product = store_model.Product.objects.get(status="published", id=id)
    except store_model.Product.DoesNotExist:
        return JsonResponse({"error":"product not found"}, status = 404)
    
    existing_cart_item = store_model.Cart.objects.filter(cart_id=cart_id, product=product).first()
    if int(qty) > product.stock:
        return JsonResponse({"error":'Qty exceed current stock amount'}, status=404)
    
    if not existing_cart_item:
        cart = store_model.Cart()
        cart.product = product
        cart.qty = qty
        cart.price = product.price
        cart.color = color
        cart.size = size
        cart.sub_total = Decimal(product.price)* Decimal(qty)
        cart.shipping =  Decimal(product.shipping)* Decimal(qty)
        cart.total = cart.sub_total * cart.shipping
        cart.user = request.user if request.user.is_authenticated else None
        cart.cart_id = cart_id
        cart.save()

        message = "Item added to cart"
    else:
        existing_cart_item = store_model.Cart()
        existing_cart_item.product = product
        existing_cart_item.qty = qty
        existing_cart_item.price = product.price
        existing_cart_item.color = color
        existing_cart_item.size = size
        existing_cart_item.sub_total = Decimal(product.price)* Decimal(qty)
        existing_cart_item.shipping =  Decimal(product.shipping)* Decimal(qty)
        existing_cart_item.total = existing_cart_item.sub_total * existing_cart_item.shipping
        existing_cart_item.user = request.user if request.user.is_authenticated else None
        existing_cart_item.cart_id = cart_id
        existing_cart_item.save()

        message ="Cart updated"
    
    total_cart_items = store_model.Cart.objects.filter(Q(cart_id=cart_id) | Q(cart_id=cart_id))
    cart_sub_total = store_model.Cart.objects.filter(Q(cart_id=cart_id) | Q(cart_id=cart_id)).aggregate(sub_total= Sum("sub_total")['sub_total'])

    return JsonResponse({
        'message':message ,
        "total_cart_items":total_cart_items.count(),
        "cart_sub_total":"{:,.2f}".format(cart_sub_total),
        "item_sub_total":"{:,.2f}".format(existing_cart_item.sub_total) if existing_cart_item else "{:,.2f}".format(cart.cart_sub_total) ,
    })

templates/store/homepage.html
{% extends 'partials/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mr.Ecomm</title>
  <link rel="shortcut icon" href="{% static 'image/favicon.png' %}" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"  rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
</head>

<body class=" bg-neutral-100  ">



  <!-- <div class=" container max-w-full px-20">
  {% if messages %}
    {% for message in messages %}
    <div class="bg-green-200 border-t-4 border-blue-500 rounded-b text-blue-900 px-4 py-3 shadow-md" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %} -->


  <!--Image slider -->

  <div id="default-carousel" class="relative w-full px-16 py-5 pt-20 z-0" data-carousel="slide">
    <!-- Carousel wrapper -->
    <div class="relative h-52 overflow-hidden rounded-lg px-10 md:h-96">
      <!-- Item 1 -->
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="{% static 'image\slider\pic1.png' %}"
          class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 object-top" alt="slider1">
      </div>
      <!-- Item 2 -->
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="{% static 'image/slider/electronic.png' %}"
          class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>
      <!-- Item 3 -->
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="{% static 'image/slider/elctronic2.png' %}"
          class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>
      <!-- Item 4 -->
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="{% static 'image/slider/mobile.png' %}"
          class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>
      <!-- Item 5 -->
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="{% static 'image/slider/shoes.png' %}"
          class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>
    </div>
    <!-- Slider indicators -->
    <div class="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
      <button type="button" class="w-3 h-3 rounded-full bg-gray-300" aria-current="true" aria-label="Slide 1"
        data-carousel-slide-to="0"></button>
      <button type="button" class="w-3 h-3 rounded-full bg-gray-300" aria-current="false" aria-label="Slide 2"
        data-carousel-slide-to="1"></button>
      <button type="button" class="w-3 h-3 rounded-full bg-gray-300" aria-current="false" aria-label="Slide 3"
        data-carousel-slide-to="2"></button>
      <button type="button" class="w-3 h-3 rounded-full bg-gray-300" aria-current="false" aria-label="Slide 4"
        data-carousel-slide-to="3"></button>
      <button type="button" class="w-3 h-3 rounded-full bg-gray-300" aria-current="false" aria-label="Slide 5"
        data-carousel-slide-to="4"></button>
    </div>
    <!-- Slider controls -->
    <button type="button"
      class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none"
      data-carousel-prev>
      <span
        class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
        <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M5 1 1 5l4 4" />
        </svg>
        <span class="sr-only">Previous</span>
      </span>
    </button>
    <button type="button"
      class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none"
      data-carousel-next>
      <span
        class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
        <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="m1 9 4-4-4-4" />
        </svg>
        <span class="sr-only">Next</span>
      </span>
    </button>
  </div>

  <!-- Catagories -->

    <h1 class=" text-xl font-bold text-center mt-14">Catagories</h1>
    <div id="catagories_sec" class="px-16 grid grid-cols-7 py-10 mx-auto gap-2">
      {% for c in catagory %}
      <a href="{% url 'store:products' c.slug %}" id="catagories"
        class=" flex shadow-lg max-h-fit items-center gap-4 px-5 rounded-lg bg-white hover:scale-105 mx-auto sm:flex-col ">
        <img src="{{ c.image.url }}" alt="" class=" h-20 w-20 object-contain">
        <h3 class="text-black font-bold text-sm">{{ c.title }}</h3>
      </a>
    {% endfor %}  
    </div>

    
  <!-- feature brands -->
   <h1 class="mb-5 text-xl font-bold mt-14 px-16 text-center">Available Brands</h1>
  <div class=" ">
    
  </div>

  <!-- productlist -->
    <h1 class="mb-5 text-xl font-bold text-center mt-14">Feature Product 🔥</h1>
  <div class="px-16 grid grid-cols-5 py-10 mx-auto w-[90%]">
    {% for p in feature_products %}
    <a href="{% url 'store:products_detail' p.slug %}"
      class=" w-52 transform overflow-hidden rounded-lg bg-white dark:bg-slate-800 shadow-md duration-300 hover:scale-105 hover:shadow-xl flex flex-col relative">
      <div class="absolute top-1 right-5"><i class="ri-heart-line"></i></div>
      <img class="h-24 w-[90%] object-contain" src="{{ p.image.url }}" alt="Product Image" />
  
      <div class="p-4">
        <h2 class="mb-2 text-sm font-medium dark:text-white text-gray-900">{{p.name}}</h2>
        <div class="text-amber-400">
          {% if not p.average_rating %}
          <i class="ri-star-s-fill"></i>
          <i class="ri-star-s-fill"></i>
            <i class="ri-star-s-line"></i>
            <i class="ri-star-s-line"></i>
            <i class="ri-star-s-line"></i>
          {% elif p.average_rating > 0 and p.average_rating < 2 %} <i class="ri-star-s-fill"></i>
            <i class="ri-star-s-line"></i>
            <i class="ri-star-s-line"></i>
            <i class="ri-star-s-line"></i>
            <i class="ri-star-s-line"></i>
            {% elif p.average_rating > 1 and p.average_rating < 3 %} <i class="ri-star-s-fill"></i>
              <i class="ri-star-s-fill"></i>
              <i class="ri-star-s-line"></i>
              <i class="ri-star-s-line"></i>
              <i class="ri-star-s-line"></i>
              {% elif p.average_rating > 2 and p.average_rating < 4 %} <i class="ri-star-s-fill"></i>
                <i class="ri-star-s-fill"></i>
                <i class="ri-star-s-fill"></i>
                <i class="ri-star-s-line"></i>
                <i class="ri-star-s-line"></i>
                {% elif p.average_rating > 3 and p.average_rating < 5 %} <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-line"></i>
                  {% elif p.avarage_rating > 4 %}
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  <i class="ri-star-s-fill"></i>
                  {% endif %}
        </div>
        <div class="flex items-center mx-auto gap-1">
          <p class="mr-2 text-sm font-semibold text-gray-900 dark:text-white">₹{{p.price}}</p>
          <p class="text-sm  font-medium text-gray-500 line-through dark:text-gray-300">₹{{p.regular_price}}</p>
          <p class="ml-auto text-xs font-medium text-green-500">{{p.percentage}}%off</p>
          <button
            class=" rounded-lg px-2 py-1.5 cursor-pointer text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 text-center mr-2 mb-2"><i
              class="ri-shopping-cart-2-fill"></i></button>
        </div>
      </div>
    </a>
  {% endfor %}  
  </div>
  

</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
{% endblock content %}

</html>

templates/store/product.html
{% extends 'partials/base.html' %}
{% block content %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MrEom|{{ c.title }}</title>
    <link rel="shortcut icon" href="{% static 'image/favicon.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap" rel="stylesheet" />

</head>

<body>
   
    <div class="py-5 pt-10">

        <section
            class="w-fit grid grid-cols-5 gap-y-5 gap-x-4 justify-center mt-10 mb-5 mx-auto justify-items-center">
          {% for p in products %}   
            <div class="w-52 bg-gray-50 shadow-md rounded-xl duration-500 hover:scale-105 hover:shadow-lg border ">
                <a href="{% url 'store:products_detail' p.slug %}" class="flex flex-col items-center space-x-5 space-y-2">
                    <img src="{{ p.image.url }}" alt="" class="h-40 w-44 object-contain rounded-t-xl" />
                    <div class=" w-52 mx-auto">
                        <span class="text-zinc-500 mr-3 uppercase text-xs font-medium">{{ p.Brand }}</span>
                        <p class="text-base font-medium text-zinc-700 truncate capitalize">{{ p.name }}</p>
                        <div class="text-amber-400">
                            {% if not p.average_rating %}
                            <i class="ri-star-s-fill"></i>
                            <i class="ri-star-s-fill"></i>
                              <i class="ri-star-s-line"></i>
                              <i class="ri-star-s-line"></i>
                              <i class="ri-star-s-line"></i>
                            {% elif p.average_rating > 0 and p.average_rating < 2 %} <i class="ri-star-s-fill"></i>
                              <i class="ri-star-s-line"></i>
                              <i class="ri-star-s-line"></i>
                              <i class="ri-star-s-line"></i>
                              <i class="ri-star-s-line"></i>
                              {% elif p.average_rating > 1 and p.average_rating < 3 %} <i class="ri-star-s-fill"></i>
                                <i class="ri-star-s-fill"></i>
                                <i class="ri-star-s-line"></i>
                                <i class="ri-star-s-line"></i>
                                <i class="ri-star-s-line"></i>
                                {% elif p.average_rating > 2 and p.average_rating < 4 %} <i class="ri-star-s-fill"></i>
                                  <i class="ri-star-s-fill"></i>
                                  <i class="ri-star-s-fill"></i>
                                  <i class="ri-star-s-line"></i>
                                  <i class="ri-star-s-line"></i>
                                  {% elif p.average_rating > 3 and p.average_rating < 5 %} <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-line"></i>
                                    {% elif p.avarage_rating > 4 %}
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    <i class="ri-star-s-fill"></i>
                                    {% endif %}
                          </div>
                        <div class="flex items-center gap-3">
                            <p class="text-lg font-semibold text-zinc-700 cursor-auto my-3"> ₹{{ p.price }}</p>
                            <del>
                                <p class="text-sm text-neutral-500 cursor-auto ml-2">₹{{ p.regular_price }}</p>
                            </del>
                            <p class=" text-sm font-medium text-green-500">{{p.percentage}}%off</p>
                        </div>
                    </div>
                </a>
            </div>
              {% endfor %}
        </section>
    </div>
  
    {% endblock content %}
</body>

</html>